export enum Status {
    PENDING = 'pending',
    FAILED = 'failed',
    COMPLETED = 'completed'
}

export enum Provider {
    WEBSMS = 'websms',
    AT = 'africastalking',
    SLACK = 'slack',
    GMAIL = 'gmail',
}

export enum Channel {
    SLACK = 'slack',
    SMS = 'sms',
    MAIL = 'mail',
    APP = 'app',
}

export enum EventType {
    AIRTIME_PURCHASE = 'AIRTIME_PURCHASE',
    AIRTIME_PURCHASE_FAILURE = 'AIRTIME_PURCHASE_FAILURE',
    UTILITY_PAYMENT = 'UTILITY_PAYMENT',
    UTILITY_PAYMENT_FAILURE = 'UTILITY_PAYMENT_FAILURE',
    VOUCHER_PURCHASE = 'VOUCHER_PURCHASE',
    VOUCHER_REFUND = 'VOUCHER_REFUND',
    WITHDRAWAL_PAYMENT = 'WITHDRAWAL_PAYMENT',
    WITHDRAWAL_FAILURE = 'WITHDRAWAL_FAILURE',
    REFERRAL_INVITE = 'REFERRAL_INVITE',
    REFERRAL_JOINED = 'REFERRAL_JOINED',
    SUBSCRIPTION_PAYMENT = 'SUBSCRIPTION_PAYMENT',
    MERCHANT_PAYMENT = 'MERCHANT_PAYMENT',
    PAYMENT_FAILURE = 'PAYMENT_FAILURE',
    ERROR_ALERT = 'ERROR_ALERT',
    STATUS_UPDATE = 'STATUS_UPDATE',
    SP_REQUEST_FAILURE = 'SP_REQUEST_FAILURE',
    TEST = 'TEST',
    DEFAULT = 'DEFAULT',
}